@startuml
skinparam conditionStyle diamond
skinparam monochrome true

|Cliente|
start
:Crear Pedido;
:Seleccionar Productos;

|Sistema|
:Recibir Productos;

fork
    :Identificar Producto Físico;
    :Sumar Precio + Coste de Envío;
fork again
    :Identificar Producto Digital;
    :Aplicar Descuento;
end fork

:Calcular Total Final;

|Cliente|
:Mostrar Resumen del Pedido;
stop

@enduml