@startuml
left to right direction
skinparam packageStyle rectangle

actor "Cliente" as c

rectangle "Tienda" {
    usecase "Registrar cliente" as regcliente
    usecase "Gestionar pedido" as gespedido
    
    usecase "Calcular importe total" as calcimporte
    usecase "Mostrar resumen" as resumen
    
    usecase "Aplicar Descuento Digital" as descdigital
    usecase "Calcular Envío Físico" as envio

    c -- regcliente
    c -- gespedido


    gespedido ..> calcimporte : <<include>>
    gespedido ..> resumen : <<include>>

    descdigital ..> calcimporte : <<extend>>
    envio ..> calcimporte : <<extend>>
}
@enduml