@startuml
hide empty description
skinparam state {
  BackgroundColor White
  BorderColor Black
}

[*] --> Instanciada : new Order(client)

state Instanciada
note right of Instanciada : Lista de productos vacía

Instanciada --> EnConstruccion : addProduct(primero)

state EnConstruccion {
    EnConstruccion --> EnConstruccion : addProduct(otro)
}

EnConstruccion --> Calculada : calcTotal()

state c <<choice>>
Calculada --> c : Verificación en Main (total == 59.5)

c --> Correcta : [true]
note right of Correcta
  Salida: "¡Mosquis! Todo correcto"
end note

c --> Incorrecta : [false]
note right of Incorrecta
  Salida: "Multiplícate por cero"
end note

Correcta --> [*]
Incorrecta --> [*]

@enduml