@startuml
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

actor "Main / Cliente" as User
participant ":Order" as Order
participant "p:Product" as Product

User -> Order : calcTotal()
activate Order

loop Para cada producto en la lista
    Order -> Product : calcPrice()
    activate Product
    
    note right
        Polimorfismo:
        - Físico: precio + envío
        - Digital: precio * 0.95
    end note
    
    Product --> Order : float precio
    deactivate Product
    
    Order -> Order : total += precio
end

Order --> User : float totalCalculado
deactivate Order

alt Pago Exitoso / Total Correcto
    User -> User : Mostrar "Pedido Confirmado"
    
else Pago Fallido / Error
    User -> User : Mostrar "Error en el pago"
end
@enduml